eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: songs
          uri: lb://SONGS-SERVICE
          predicates:
            - Path=/songs/**
        - id: songLists
          uri: lb://SONGS-SERVICE
          predicates:
            - Path=/songLists/**
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: lyrics
          uri: lb://LYRICS-SERVICE
          predicates:
            - Path=/lyrics/**