server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: songs
          uri: lb://SONGS
          predicates:
            - Path=/songs/**
        - id: songLists
          uri: lb://SONGS
          predicates:
            - Path=/songLists/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**